# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceKu.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(401, 641)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(0, 51, 151, 10))
        self.label_13.setStyleSheet("background-color: rgb(49, 156, 255);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 360, 381, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.edt_shape_detect = QtWidgets.QLineEdit(self.groupBox_4)
        self.edt_shape_detect.setGeometry(QtCore.QRect(210, 40, 161, 20))
        self.edt_shape_detect.setObjectName("edt_shape_detect")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(30, 40, 111, 21))
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(30, 70, 131, 21))
        self.label_16.setObjectName("label_16")
        self.edt_area = QtWidgets.QLineEdit(self.groupBox_4)
        self.edt_area.setGeometry(QtCore.QRect(210, 70, 161, 20))
        self.edt_area.setObjectName("edt_area")
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setGeometry(QtCore.QRect(120, 590, 171, 41))
        self.btn_start.setObjectName("btn_start")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(300, 51, 132, 10))
        self.label_15.setStyleSheet("background-color: rgb(250, 191, 13);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(80, 89, 255);")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(150, 51, 154, 10))
        self.label_14.setStyleSheet("background-color: rgb(255, 160, 30);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_webcam = QtWidgets.QLabel(Form)
        self.label_webcam.setGeometry(QtCore.QRect(10, 70, 381, 281))
        self.label_webcam.setFrameShape(QtWidgets.QFrame.Box)
        self.label_webcam.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_webcam.setLineWidth(1)
        self.label_webcam.setText("")
        self.label_webcam.setObjectName("label_webcam")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(210, 480, 181, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.slider_threshold = QtWidgets.QSlider(self.groupBox_5)
        self.slider_threshold.setGeometry(QtCore.QRect(20, 40, 81, 19))
        self.slider_threshold.setMaximum(255)
        self.slider_threshold.setProperty("value", 50)
        self.slider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold.setObjectName("slider_threshold")
        self.edt_nilai_threshold = QtWidgets.QLineEdit(self.groupBox_5)
        self.edt_nilai_threshold.setGeometry(QtCore.QRect(120, 40, 41, 20))
        self.edt_nilai_threshold.setObjectName("edt_nilai_threshold")
        self.slider_threshold_2 = QtWidgets.QSlider(self.groupBox_5)
        self.slider_threshold_2.setGeometry(QtCore.QRect(20, 70, 81, 19))
        self.slider_threshold_2.setMaximum(255)
        self.slider_threshold_2.setProperty("value", 100)
        self.slider_threshold_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold_2.setObjectName("slider_threshold_2")
        self.edt_nilai_threshold_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.edt_nilai_threshold_2.setGeometry(QtCore.QRect(120, 70, 41, 20))
        self.edt_nilai_threshold_2.setObjectName("edt_nilai_threshold_2")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 480, 181, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.slider_OR = QtWidgets.QSlider(self.groupBox_6)
        self.slider_OR.setGeometry(QtCore.QRect(20, 70, 141, 20))
        self.slider_OR.setMaximum(5000)
        self.slider_OR.setProperty("value", 3)
        self.slider_OR.setOrientation(QtCore.Qt.Horizontal)
        self.slider_OR.setObjectName("slider_OR")
        self.edt_WOR = QtWidgets.QLineEdit(self.groupBox_6)
        self.edt_WOR.setGeometry(QtCore.QRect(20, 40, 41, 20))
        self.edt_WOR.setObjectName("edt_WOR")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(70, 40, 21, 21))
        self.label_17.setObjectName("label_17")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Measurement Object Area"))
        self.groupBox_4.setTitle(_translate("Form", "Details"))
        self.label_12.setText(_translate("Form", "Shape Detected"))
        self.label_16.setText(_translate("Form", "Object Area cm2"))
        self.btn_start.setText(_translate("Form", "Start Camera"))
        self.label.setText(_translate("Form", "Computer Vision - Measurement Object Area"))
        self.groupBox_5.setTitle(_translate("Form", "Canny Settings"))
        self.edt_nilai_threshold.setText(_translate("Form", "50"))
        self.edt_nilai_threshold_2.setText(_translate("Form", "100"))
        self.groupBox_6.setTitle(_translate("Form", "Width Object Reference"))
        self.edt_WOR.setText(_translate("Form", "3"))
        self.label_17.setText(_translate("Form", "cm"))

